#flag -DMAX_GPIO=32
#flag -I@VROOT
#flag -I@VROOT/jswin32
#flag -I@VROOT/lib
#flag -I@VROOT/duktape
#flag -I@VROOT/platform/luat
#flag -I@VROOT/duktape_task
#flag -I@VROOT/platform
#flag -IE:\MinGW\include 
#flag -IE:\MinGW\include\c++\9.2.0 
#flag -IE:\MinGW\include\c++\9.2.0\x86_64-w64-mingw32

#include "app.h"

#flag @VROOT/app.c
#flag @VROOT/fsdep.c
#flag @VROOT/duktape/duktape.c
#flag @VROOT/duktape/init.c
#flag @VROOT/duktape/utils.c
#flag @VROOT/duktape/module-node/mod_load.c
#flag @VROOT/duktape/module-node/duk_module_node.c
#flag @VROOT/duktape/eval_file.c
#flag @VROOT/duktape_task/duktape_task.c
#flag @VROOT/duktape_task/on_msg.c
#flag @VROOT/lib/gpio.c
#flag @VROOT/lib/keypad.c
#flag @VROOT/lib/g711a.c
#flag @VROOT/lib/uart.c
#flag @VROOT/lib/fs.c
#flag @VROOT/lib/misc.c
#flag @VROOT/lib/udp.c
#flag @VROOT/lib/network.c
#flag @VROOT/lib/audio.c
#flag @VROOT/lib/tts.c
#flag @VROOT/lib/os.c
#flag @VROOT/lib/pmd.c
#flag @VROOT/lib/iot_module.c
#flag @VROOT/platform/win32/log.c
#flag @VROOT/platform/win32/os.c
#flag @VROOT/platform/win32/gpio.c
#flag @VROOT/platform/win32/fs.c
#flag @VROOT/platform/win32/keypad.c
#flag @VROOT/platform/win32/uart.c
#flag @VROOT/platform/win32/misc.c
#flag @VROOT/platform/win32/udp.c
#flag @VROOT/platform/win32/network.c
#flag @VROOT/platform/win32/audio.c
#flag @VROOT/platform/win32/tts.c
#flag @VROOT/platform/win32/pmd.c

fn C.appimg_enter(voidptr)
fn C.appimg_exit()
